CREATE TABLE PRODI (`Id` INT NOT NULL, `NamaProdi` VARCHAR(50) NOT NULL, UNIQUE(NamaProdi));

INSERT INTO PRODI VALUES (1,'Ilmu Komputer');
INSERT INTO PRODI VALUES (2,'Sistem Informasi');
INSERT INTO PRODI VALUES (3,'Aktuaris');
INSERT INTO PRODI VALUES (4,'E-sports');
INSERT INTO PRODI VALUES (5,'Teologi');
INSERT INTO PRODI VALUES (6,'Kesekretariatan');
